### ISSUE TITLE
Global Theme Settings

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/EnticEdge-Beyondbooksmart#1]
I started by editing the structure files and adjusting the general color settings of the theme. I also worked on typography, containers, and colors. After that, I configured the JSON variables for theme changing and its usage. 

Global Theme Settings
https://app.hubspot.com/theme-editor/331584/edit/Beyond%20Book%20Smart%20-%20Theme?testmode=true

**Comment by awais-abbas-com** [comment]
https://app.hubspot.com/theme-editor/331584/edit/Beyond%20Book%20Smart%20-%20Theme?testmode=true

General theme settings has been completed.
