### ISSUE TITLE
Home - BBS Reviews - whole section is not per the design. need to be updated

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#102]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
whole section is not per the design. need to be updated
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/9cce13f8-cb2c-43da-9a0d-620e685befae)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7add7e29-7978-4087-ad76-eeea325f232e)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/5ec13a07-d647-4025-abdf-76b958b6b152)

**Comment by awais-abbas-com** [comment]
Its a plugin
