### ISSUE TITLE
Home - Header - in mobile device, instead of menu bar there should be cube icon as per design file

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#103]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
in mobile devices, instead of the menu bar, there should be a cube icon as per the design file

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/0e3d2c6e-30dc-4f1c-bf27-357b339da4bd)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/9a83e8ee-b990-4cc9-bd35-ed3f7260f359)

**Comment by awais-abbas-com** [comment]
fixed
