### ISSUE TITLE
Home - Footer - after logo padding is incorrect it should be 47 px and 22 px in mobile

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#106]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description**:
after logo padding is incorrect it should be 47 px and 22 px in mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/6aee1f29-c210-48e2-997b-e386781674c5)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/db8c3530-414c-4526-a1b0-064794668af8)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/916e9e7a-db86-4b37-8b4e-301b6196b37c)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/3f575a56-0455-4580-902f-ac4b8ae79a25)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
