### ISSUE TITLE
Home - Footer - padding between two paragraphs is incorrect it should be 78 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#107]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
padding between two paragraphs is incorrect it should be 78 px

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/65beb2a3-5a19-4336-bd51-54e68176ba6a)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/6a2c3935-9ec6-49f1-be65-597a48804834)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We have conducted a thorough check of the spacing and alignment using fonts and AI, achieving a close match. The typography, spacing, and alignment are kept generic to maintain a consistent user experience.
