### ISSUE TITLE
Home - Footer - font size and line height are incorrect they should be 19px and 33.25 respectively

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#110]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
font size and line height are incorrect they should be 19px and 33.25 respectively

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/b5f40949-7404-4b0c-9a0f-716e1ee74e7a)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/0cbf571b-fd84-4de7-9bd3-01cf2d32502b)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We have conducted a thorough check of the spacing and alignment using fonts and AI, achieving a close match. The typography, spacing, and alignment are kept generic to maintain a consistent user experience.
