### ISSUE TITLE
Home - Footer - padding between menu points and social icons is incorrect it should be 156 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#111]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
padding between menu points and social icons is incorrect it should be 156 px

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/b0fac993-3b8b-4334-bdd8-06c6cde504ec)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/4d082c9a-7c52-4776-881d-5665269d376e)

**Comment by muhammad-suleman-com** [comment]
Our design files are created using Illustrator. We have carefully examined the spacing and alignment using fonts and AI, aiming for a close match. The typography, spacing, and alignment are kept consistent to provide a uniform user experience.
