### ISSUE TITLE
Home - Footer - social icons should be center-aligned

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#112]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
social icons should be center-aligned

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/a8c1614d-f57e-4027-9adc-5d493006125f)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/2ec67814-2f59-4e01-a820-cefe08853509)

**Comment by awais-abbas-com** [comment]
Fixed
