### ISSUE TITLE
Page - Events

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#12]
Need to create Events page following Desktop and Mobile Designs.

Follow General guidelines including :
Follow Mobile First and optimized approach for code.
Commented Code
Create Modules with generic options including typography/containers/spaces/background and button panels.
Every text/image should be editable in HubSpot Edit Settings.

Design URLs
Desktop: https://www.dropbox.com/home/PROJECTS/Beyond%20BookSmart/Desktop/BBS%20Website%20-%20Desktop/BBS%20Website%20-%20Desktop/bbs_events_01_Folder
Mobile: https://www.dropbox.com/home/PROJECTS/Beyond%20BookSmart/Mobiled%20Web%20Pages/design/Events

Need Logins to Check Designs.

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the Events. Please follow the instructions mentioned above for details.

Page URL's:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/events

**Comment by awais-abbas-com** [comment]
Task has been completed
https://www.beyondbooksmart.com/workshops-and-events
