### ISSUE TITLE
Home - Section We Can Help - Mobile - headings copy text has incorrect color. It should be #000000

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#120]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
headings copy text has incorrect color. It should be #000000
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1098772c-f6a7-49b7-952d-ab59abe0e740)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/117a3d4e-4a20-42ae-a9f7-7a4cf708d4c8)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/34ea69ec-8e32-45c4-b181-763e31454b4d)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
