### ISSUE TITLE
Home - Section Meet The Coaches - image size is incorrect it should be W: 276.92px H: 244.19px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#125]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
image size is incorrect it should be W: 276.92px H: 244.19px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/91082f47-01f5-40f2-996c-a668bd4cdf87)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/238f0873-8dc9-4789-b801-81822e7dd906)

**Comment by awais-abbas-com** [comment]
Fixed
