### ISSUE TITLE
Home - Section Meet The Coaches - div size is incorrect it should be W: 289.86px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#126]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
div size is incorrect it should be W: 289.86px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/cc40f54d-b799-4ad3-9e82-f31a9836553f)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/4cfa6a15-45bb-455b-9765-bbc332f2df48)

**Comment by awais-abbas-com** [comment]
Fixed
