### ISSUE TITLE
Home - Section Meet The Coaches - text width size is incorrect it should be 221.94px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#127]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
text width size is incorrect it should be 221.94px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/397e84fc-a47c-49a7-899e-a25c2634f67e)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/15084838-5748-4a96-a92f-3be7ddd4dc35)

**Comment by awais-abbas-com** [comment]
Fixed
