### ISSUE TITLE
Home - Section Meet The Coaches - font size and line height are incorrect it should be 15px and 21 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#128]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
font size and line height are incorrect it should be 15px and 21 px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/fa1b8dc6-3d84-4b3f-89e8-070476aabfe2)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/95da9573-3794-423e-8169-d81a8b2845aa)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
