### ISSUE TITLE
Home - Section Meet The Coaches - font size and line height are incorrect it should be 12px and 21 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#129]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
font size and line height are incorrect it should be 12px and 21 px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/68d0b0dc-7c86-4ef9-83ed-f8eacbbe6ce9)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/37fd5061-938b-4c94-afd6-40c581b185ff)

**Comment by muhammad-suleman-com** [comment]
We have reviewed the spacing and alignment by using fonts and AI, striving for a close match. The typography, spacing, and alignment are standardized to ensure a consistent user experience.
