### ISSUE TITLE
Home - Section As Featured In - Mobile - incorrect font size and line height of the heading. it should be 25px and 30px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#130]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect font size and line height of the heading. it should be 25px and 30px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6426318b-a7f5-4296-8ad8-b7e9b2e79ba6)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/bc1fadc5-3f54-44c2-bd59-971efa1e5413)

**Comment by muhammad-suleman-com** [comment]
Our design files are created using Illustrator. We have carefully examined the spacing and alignment using fonts and AI, aiming for a close match. The typography, spacing, and alignment are kept consistent to provide a uniform user experience.
