### ISSUE TITLE
Home - Section Meet The Coaches - the padding between two section should be 48 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#131]
**URL Tested:**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

**Description:**
the padding between two section should be 48 px

**Device**
Mobile

**Expected Result:**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/bfa0a2be-d59f-4918-89a3-31ce66870597)

**Actual Result**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/b936ccee-7473-4b98-9257-7143ac6b1595)

**Comment by muhammad-suleman-com** [comment]
We create our design files using Illustrator. We have verified the spacing and alignment using fonts and AI, ensuring a close match. The typography, spacing, and alignment are standardized for a consistent user experience.
