### ISSUE TITLE
Home - Section Let's Get Started - Mobile - lets get started heading has incorrect line height. It should be 38px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#133]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
let's get started heading has incorrect line height. It should be 38px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/fb8f1dd7-527b-4d0b-a6f9-8514c9333cf4)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4dd5cf49-becc-4016-8952-df4e5eb31a82)

**Comment by muhammad-suleman-com** [comment]
We create our design files using Illustrator. We have verified the spacing and alignment using fonts and AI, ensuring a close match. The typography, spacing, and alignment are standardized for a consistent user experience.
