### ISSUE TITLE
Home - Section Let's Get Started - Mobile - "Learn More" button has incorrect line height. it should be 15px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#134]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The "Learn More" button has an incorrect line height. it should be 15px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/80863938-dd9a-4088-9b79-2c47d97b6ba8)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/195856f0-fb96-4431-9dd3-8015ebc81271)

**Comment by muhammad-suleman-com** [comment]
We have examined the spacing and alignment using fonts and AI, making sure they closely match. The typography, spacing, and alignment are standardized to provide a consistent user experience.
