### ISSUE TITLE
Home - BBS reviews- Mobile - whole section is not as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#136]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
whole section is not as per design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/00540336-e693-4322-8b1f-90ffa6c9b08f)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/47fd29e9-e06b-44f6-8091-b748b5b80eac)

**Comment by awais-abbas-com** [comment]
Plugin implemented
