### ISSUE TITLE
Home - Section How It Works - Mobile - incorrect font size and line height of the heading. it should be 25px and 30px 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#137]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 incorrect font size and line height of the heading. it should be 25px and 30px 
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/65f1c0e2-2803-433b-9992-830e0e290954)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/240e2416-4212-4a16-a5fd-63c2b9806c19)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
