### ISSUE TITLE
Home - Section How It Works - heading should be in 1 line as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#138]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
heading should be in 1 line as per the design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/2224e3e1-2b32-41a5-9e2f-6bdacfc56a3b)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/370cab62-fbf3-44fa-a0f9-0bbc81d05b5d)

**Comment by awais-abbas-com** [comment]
Sometime AI or design file may have some effects and they extend from standard container. Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience.
