### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - heading has incorrect font size, line height and color. It should be 23px and 27px and #1E1E30

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#141]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
heading has incorrect font size, line height, and color. It should be 23px and 27px and #1E1E30
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7a6be783-f014-41a0-84c0-f27ced10d5c5)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/249e70ef-68bc-4fc1-9ac8-2634bee7009a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
