### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - cards heading has incorrect font size and line height. It should be 10px and 12px accordingly

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#143]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards heading has incorrect font size and line height. It should be 10px and 12px accordingly
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/08c688ee-2164-4f75-97c8-f5f19ac18443)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f6c02eb1-9cee-4d9c-ac7a-09aca54d512d)

**Comment by awais-abbas-com** [comment]
Fixed
