### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - cards copy text has incorrect font weight  and line height and color. It should be regular 17px and #000000

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#144]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards copy text has incorrect font weight  and line height and color. It should be regular 17px and #000000
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7b8d8f98-f26a-42fc-aed8-d7471e706498)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/72b752a8-bf2b-4d3a-9880-000664f0f5ba)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
