### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - cards learn more button text has incorrect font size and line height and color. it should be 9px 9px and #1E1E30

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#145]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards learn more button text has incorrect font size and line height and color. it should be 9px 9px and #1E1E30
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/55456c07-0866-413f-b900-5b4f6a7f24df)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cb782f8d-2232-49c9-99c2-87c97f614c19)

**Comment by awais-abbas-com** [comment]
Duplicate but fixed button styles already
