### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - cards learn more button has incorrect width and height and radius. It should be width= 103px height =  30px. and radius should be 15px on all sides

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#146]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards learn more button has incorrect width height and radius. It should be width= 103px height =  30px. and the radius should be 15px on all sides
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/39d8fd42-3f52-4c21-aec0-774eb401e00a)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/05b9d7fb-3581-4c8c-a8db-18bd33f9ee06)

**Comment by awais-abbas-com** [comment]
Fixed
