### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - on cards not enough spacing between the copy text and the learn more button.

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#147]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
on cards not enough spacing between the copy text and the learn more button.
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/8d51f959-0f72-4075-b913-3b787ee865e9)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c108fb06-a825-4227-9982-4e71b44844f9)

**Comment by awais-abbas-com** [comment]
Fixed
