### ISSUE TITLE
Home - Section Serve Our Client's - Mobile - cards have incorrect border radius. this should be 15.77px 15.77px 0px 0px as per the design.

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#148]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards have incorrect border radius. this should be 15.77px 15.77px 0px 0px as per the design.
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ef10bd01-ec43-49b6-92ea-97fa3c49a1fe)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/665a7e65-f04c-477f-a956-1906a4964af9)

**Comment by awais-abbas-com** [comment]
Fixed
