### ISSUE TITLE
Home - Sections What Are Those - Mobile - copy text has incorrect font size, font weight, line height and color. It should be 12px,light, 20px and #000000

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#150]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
copy text has incorrect font size, font weight, line height, and color. It should be 12px,light, 20px and #000000

Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/2db3a08e-252d-4fc9-af1d-b457fd79aa20)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/855979e1-7798-4d77-b364-5312ee261d70)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
