### ISSUE TITLE
Home - Sections What Are Those - Mobile - The checklist icon has the incorrect size and color. It should be W= 8, H=5 and color should be #1F9CC0. Additionally, it overlaps with the text.

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#152]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The checklist icon has the incorrect size and color. It should be W= 8, H=5 and color should be #1F9CC0. Additionally, it overlaps with the text.
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3daa8e03-70d2-4619-8fc0-732da945f427)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/efa8dd46-5f84-4bfd-b4fc-5e1fecf7c2a9)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience.
