### ISSUE TITLE
Home - Section Listen In/Read On - Mobile- Read on - the learn more button has the incorrect font size and line height. It should be 14px and 20px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#154]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Read on - the learn more button has the incorrect font size and line height. It should be 14px and 20px

Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ef2265c8-cb8b-46b2-a510-39be7f109264)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/0b3754d3-7e98-42b6-9358-9f723277fb75)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
