### ISSUE TITLE
Home  - the side paddings should remain constant for different desktop, Mobile, and tab resolutions as standard. Currently, it is shrinking and expanding unexpectedly

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#156]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
the side paddings should remain constant for different desktop, Mobile, and tab resolutions as standard. Currently, it is shrinking and expanding unexpectedly.
Device: Any

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/a59e51ed-5ba5-4f6f-b6fc-188b7b4c3ca0)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d6a7b842-ee9e-4266-93a5-d5a959452522)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ef5c4238-96b6-4b3d-8643-83355fb3b8ef)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c4b053ab-160b-4580-ab10-66ab235a724c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
