### ISSUE TITLE
Page - Join our team

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#16]
Need to create Join Our Team page following Desktop and Mobile Designs.

Follow General guidelines including :
Follow Mobile First and optimized approach for code.
Commented Code
Create Modules with generic options including typography/containers/spaces/background and button panels.
Every text/image should be editable in HubSpot Edit Settings.

Design URLs
Desktop: https://www.dropbox.com/home/PROJECTS/Beyond%20BookSmart/Desktop/BBS%20Website%20-%20Desktop/BBS%20Website%20-%20Desktop/bbs_join_our_team_02_Folder
Mobile: https://www.dropbox.com/home/PROJECTS/Beyond%20BookSmart/Mobiled%20Web%20Pages/design/Join%20our%20Team

Need Logins to Check Designs.

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the Join Our Team both versions. Please follow the instructions mentioned above for details.

Page URL's:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/join-our-team-01
https://www-beyondbooksmart-com.sandbox.hs-sites.com/join-our-team-02

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the Join Our Team. Please follow the instructions mentioned above for details.

Page URL's:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/join-our-team-01
https://www-beyondbooksmart-com.sandbox.hs-sites.com/join-our-team-02

**Comment by awais-abbas-com** [comment]
https://www.beyondbooksmart.com/employment-opportunities-at-beyond-booksmart

Task has been completed.
