### ISSUE TITLE
ADHD - The "Who we help" copy text line height is incorrect. It should be 33px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#162]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The "Who we help" copy text line height is incorrect. It should be 33px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/a50a68d5-e40f-422e-be10-14c3f2190c16)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6548009a-4943-4c95-8116-4deee2f65f4f)

**Comment by muhammad-suleman-com** [comment]
Our design files are exclusively made with Illustrator to ensure the highest quality. We have meticulously checked the font spacing and alignment to guarantee a consistent and superior user experience. With our design expertise, you can be confident that the typography, spacing, and alignment are flawless.
