### ISSUE TITLE
Contact - Contact us heading has incorrect font size and line height. It should be 107px and 107 px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#163]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The contact us heading has an incorrect font size and line height. It should be 107px and 107px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7dbfac97-ca4e-4a52-9321-af3915bfcbfd)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1b67d2eb-f249-4b01-b436-7cbf56189e17)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
