### ISSUE TITLE
Contact - incorrect font size and line heigh for the haeding copy text it should be 28px and 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#164]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect font size and line heigh for the haeding copy text it should be 28px and 47px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/795b9258-e354-4fb0-ba7a-004cd5b2faa1)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/090acaee-7885-48be-8ba5-0652ecb9de4d)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
