### ISSUE TITLE
Contact - incorrect font size and line height of "single session coaching"  copy text. it should be 28px and 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#165]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect font size and line height of the "single session coaching"  copy text. it should be 28px and 47px
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/09a7056b-1794-43d3-beb3-c3c05900349f)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ea0f319b-d4f0-4c3b-a407-2b9958171994)

**Comment by muhammad-suleman-com** [comment]
We want to inform you that our design files are created using Illustrator. We have taken the necessary steps to ensure that the spaces are checked using both installed fonts and the AI file. We have ensured that the alignment and spaces match the original design files in AI as closely as possible. Moreover, we have kept the typography, spaces, and alignment generic and equalized to provide a better user experience for the same type of block.
