### ISSUE TITLE
Contact - Section Serve Our Client's,  The heading has incorrect line height . it should be 65px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#166]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Section Serve Our Clients,  The heading has incorrect line height. it should be 65px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e3218072-6e30-43db-ab3a-332ffce41eeb)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6692c26d-a501-455d-bdab-3efe9009b890)

**Comment by muhammad-suleman-com** [comment]
Our design files are in Illustrator. We've checked spaces using both installed fonts and the AI file, ensuring alignment and spaces match the original files. Typography, spaces, and alignment are generic and equalized for a better user experience with the same type of block.s.
