### ISSUE TITLE
Contact - Section Serve Our Client's cards copy text has incorrect line height. it should be 31px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#167]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
Section Serve Our Client's cards copy text has incorrect line height. it should be 31px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1ad4242d-dc22-4979-bd96-bc6e814d3160)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6bc42c7c-22ce-4dfe-b1c1-addb637b6d92)

**Comment by muhammad-suleman-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also, We kept the typography, spaces and alignment generic and equalized to maintain a better user experience for the same kind of blocks.
