### ISSUE TITLE
Contact - Section Serve Our Client's - "Learn More " button text has incorrect font weight. it should be regular

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#168]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
Section Serve Our Client's - "Learn More " button text has incorrect font weight. it should be regular

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6307ff9c-954f-4787-b9e7-1ff7edc4ce12)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4bdee609-e1d2-47d5-9130-3ece8f22fa6f)

**Comment by muhammad-suleman-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
