### ISSUE TITLE
Contact - Mobile - incorrect font size and line height of "single session coaching" Cards headings. should be 14px and 20px 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#178]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
incorrect font size and line height of "single session coaching" Cards headings. should be 14px and 20px 
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/73a44d16-eb28-4284-b461-e335e1b47f09)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cdae21a3-6e00-41fc-87a7-474d62373a5f)

**Comment by muhammad-suleman-com** [comment]
Original design files are in Illustrator. Alignment and spaces match the original design files in AI. Typography, spaces, and alignment are generic and equalized for a better user experience.
