### ISSUE TITLE
Contact - Mobile - incorrect font size and line height of "single session coaching" Cards copy text. should be 12px and 20px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#179]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
 incorrect font size and line height of "single session coaching" Cards copy text. should be 12px and 20px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ddbf2370-b6cf-4710-8486-641e25d3f6b7)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/2bfb6e26-aaa2-420e-8286-101953a21d68)

**Comment by muhammad-suleman-com** [comment]
Original design files are in Illustrator. Alignment and spaces match the original design files in AI. Typography, spaces, and alignment are generic and equalized for a better user experience.
