### ISSUE TITLE
Contact - Mobile - incorrect font size and line height of "single session coaching" Cards Price ($99) . should be 21px and 31px. and for per session text it should be 12px and 28px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#180]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
incorrect font size and line height of "single session coaching" Cards Price ($99) . should be 21px and 31px. and for per session text it should be 12px and 28px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3b0cab9f-87f3-4805-8c37-793695335d29)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/428547f9-02e0-49ec-8456-e54d7e227a43)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/37048df3-5310-469a-a3a7-8a305afa47bd)

![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ee808b0f-5cf8-49c3-9a5a-75ef86eb43eb)

**Comment by muhammad-suleman-com** [comment]
Original design files are in Illustrator. Alignment and spaces match the original design files in AI. Typography, spaces, and alignment are generic and equalized for a better user experience.
