### ISSUE TITLE
Contact - Mobile - incorrect spacings between calender and single session, and single session heading and copy text to cards

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#183]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
1: incorrect spacings between the calendar and the single session,
2: and single session heading and copy text to cards
3: copy text to cards
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d0ab99f2-8620-4105-84ee-96ead2278012)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b749d924-ae6f-4119-b3d4-954a5caa1375)

**Comment by awais-abbas-com** [comment]
Its a plugin and now it is not on page after client updates.
