### ISSUE TITLE
Contact - single Session Coaching Cards, the radio button is not working (The price is changing but the active state is not shifting on others after clicking)

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#185]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
For single Session Coaching Cards, the radio button is not working (The price is changing but the active state is not shifting on others after clicking)

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f16f0979-f2b9-484e-8e59-28d331d63534)

**Comment by awais-abbas-com** [comment]
Fixed
