### ISSUE TITLE
Contact - Incorrect Spacing after submitting meeting scedule

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#186]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

Description:
Incorrect Spacing after submitting the meeting schedule
Device: Any

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4ab2097b-9fe8-45c9-a832-9c187f56057e)

**Comment by awais-abbas-com** [comment]
Contact Page changed after client updates
