### ISSUE TITLE
ADHD - ADHD information section, the cards copy text has incorrect font size and line height. It should be 18px and 24px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#187]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
ADHD information section, the cards copy text has incorrect font size and line height. It should be 18px and 24px
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1e74c9bb-6ed0-486b-8f20-6a34026b1b0d)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/923f4f6a-294e-4987-a030-c30deb5e08eb)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
