### ISSUE TITLE
ADHD - I have become more confident" has incorrect line height. it should be 47

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#188]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
I have become more confident" has incorrect line height. it should be 47px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7afd094c-3253-4a31-bd51-a6a36a62268b)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ec9c4978-f8b6-4506-8c13-f075d4138756)

**Comment by awais-abbas-com** [comment]
Fixed
