### ISSUE TITLE
BSS ADHD -- paragraph width length is incorrect it should be 311

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#191]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
paragraph width length is incorrect it should be 311

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/4aaf291f-3d0c-4e60-ad25-1be43d0b5236)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/6736d871-73f5-47cd-beb5-a6903fedae43)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
