### ISSUE TITLE
BSS ADHD -- banner top and bottom padding is incorrect it should be 20 from top and 41 px on bottom 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#194]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
banner top and bottom padding is incorrect it should be 20 from top and 41 px on bottom 

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/a8ef0d5d-594c-4b91-a473-9031b23b0520)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/0975fbbd-cdd9-4efa-9604-74a909d05307)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/6d06ce19-3a46-44de-ae39-e28863b8787d)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/743a534d-0b87-419c-878b-4ecc51fcf94a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
