### ISSUE TITLE
BSS ADHD -- image and paragraph side paddings are incorrect it should be 26.5 on both sides

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#195]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
image and paragraph side paddings are incorrect it should be 26.5 on both sides

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/4d31113a-ea1f-4526-adaa-51d55c61c5a0)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/5a3468ad-341b-4dfd-a697-d0c52c54452a)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/86b0ae50-f17a-4872-bb7d-957355a3a11f)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/b1934cf9-5d01-4d64-bbec-f3532a67077b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
