### ISSUE TITLE
ADHD - Listed In/ Read on section> copy text has incorrect font size and line height. It should be 21px and 33px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#196]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd
Description:
Listed In/ Read on section> copy text has incorrect font size and line height. It should be 21px and 33px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4ee64577-313d-4363-b542-84f85fdb0635)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/a133f8a0-d97e-4dbf-beb6-35690cdd9150)

**Comment by awais-abbas-com** [comment]
Fixed
