### ISSUE TITLE
BSS ADHD - How it helps -- padding between paragraph and container is incorrect

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#199]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
 bottom padding between paragraph and container is incorrect it should be 14 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/d2dbc723-1c09-4565-b9b4-86f31d8653ad)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/73ec90ba-47fb-4a6d-9d5c-2711be2001a3)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
