### ISSUE TITLE
BSS ADHD - How it helps -- tick icon size is incorrect it should be 9.79px and 6.09px respectively 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#202]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
tick icon size is incorrect it should be 9.79px and 6.09px respectively 

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/c2937ab0-22e4-41e8-81f7-5818b3f42ce9)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/a3d2e9dc-8af6-472f-98ab-e3152d61ba22)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
