### ISSUE TITLE
BSS ADHD - How it helps -- gradient color is incorrect it should be same as design file

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#203]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
gradient color is incorrect it should be same as design file

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/13b3020c-d82c-44e9-b319-d3d229a0d2ca)
**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/74b3e38b-0a47-4c09-9e29-0195b0abd556)

**Comment by awais-abbas-com** [comment]
Circle Shadows are smaller now for mobile but positions followed from desktop. 

Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
