### ISSUE TITLE
BSS ADHD - How it helps - Our Approach -- heading and paragraph should be center-aligned

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#204]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
heading and paragraph should be center-aligned

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/5ff2e958-67cb-4222-9743-ce85a328f133)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/7db1114f-19a2-4f8d-9680-b21b794d926a)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/0384783a-da52-4dac-9cf3-948c24cff931)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/381be737-eac4-4de4-8224-aa9d7fb7ff6c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
