### ISSUE TITLE
BSS ADHD - How it helps - Our Approach -- image size is incorrect

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#206]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
image size is incorrect

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/a4d28df2-33bb-4d34-85c6-f24eafa9bf78)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/f9c37f35-2d7b-4dc5-a198-aec49c95891f)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
