### ISSUE TITLE
BSS ADHD - How it helps -- paragraph font size and line height is incorrect it should be 12px and 20 px 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#208]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**

 paragraph font size and line height is incorrect it should be 12px and 20 px 

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/15bcd068-526f-471b-bf25-79f12824f636)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/98eef498-ac24-4199-8df2-677f8228bd87)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
