### ISSUE TITLE
ADHD - Our approch section, image has incorrect size

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#209]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
Our approch section, image has incorrect size
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/75097af3-0f2a-4b69-a634-06afb99812c8)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/72de5c31-6c69-477f-a566-899da86c7250)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
