### ISSUE TITLE
BSS ADHD - Who we help -- heading bottom padding is incorrect it should be 33 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#212]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
heading bottom padding is incorrect it should be 33 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/7fe520d7-ecfd-414b-85dd-472cfcb2d00d)
**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/deda4c0a-1c85-4003-aa79-67605887cfa1)

**Comment by awais-abbas-com** [comment]
Fixed
