### ISSUE TITLE
ADHD - ADHD information cards has incorrect border radius. It should be 16px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#213]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
 ADHD information cards has incorrect border radius. It should be 16px
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3636c27b-4756-4850-90a7-8bd423c9f716)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b2306a13-32e0-4f59-87c7-236e137f2715)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
