### ISSUE TITLE
ADHD - incorrect spacing on Meet the BBS Team section

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#215]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
 incorrect spacing on the Meet the BBS Team section

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cca1f1cd-7095-43c9-ac18-c1483f8a77ad)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7f68def5-53b1-4e22-b1a8-b4cb5aa9d8cd)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
