### ISSUE TITLE
BSS ADHD - Who we help --  section top and bottom padding is incorrect it should be 67 from the top and 43 from the bottom padding

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#216]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
section top and bottom padding is incorrect it should be 67 from the top and 43 from the bottom padding

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/6b93fe0e-894b-444b-a7a8-457da90e2b15)

![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/2accdd25-e163-4bdc-b9c1-b6a123c4b1b3)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/a734213e-1a3d-45f1-bd1e-25eecf59fe36)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
