### ISSUE TITLE
BSS ADHD - image size is incorrect it should be 276.92px, 244.19px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#218]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
image size is incorrect it should be 276.92px, 244.19px

**Screenshot**
**Expected**

![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/5a37d546-b77f-42e5-bdef-98d34f37ef3f)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/aeb7e300-263d-469e-8e9f-d89e95c79cee)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
