### ISSUE TITLE
BSS ADHD - text font size should be 13 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#220]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**

text font size should be 13 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/ceb456cd-60f9-4019-9b25-29273112bb53)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/c4a76da3-a6e8-4f37-a8b5-92a8f1fd552e)

**Comment by awais-abbas-com** [comment]
Fixed
