### ISSUE TITLE
BSS ADHD - Meet the BSS -- button border-radius is incorrect it should be 2.09px 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#222]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

**Bug**
button border-radius is incorrect it should be 2.09px 

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/ddf328a4-2a57-4fcf-bcef-a04d2cb16283)

**Actual**
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/129780439/583cd7c8-93db-4f0b-ad4b-a14d2ff3cd20)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
