### ISSUE TITLE
ADHD - The BBS review section is not the same as the design (need to update the whole, and not function)

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#223]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
The BBS review section is not the same as the design (need to update the whole, and not function)

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cbf9e0c5-2219-4657-88c7-91a07bb6ab3c)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/a5a6052b-ddd2-4f8e-b336-9c044b78bc3e)

**Comment by awais-abbas-com** [comment]
Reviews are from plugin
