### ISSUE TITLE
ADHD - Mobile - Listed in Read on section - incorrect font size and line height of "Learn More " button text . should be 14px and 20px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#224]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
 Listed in the Read on section - incorrect font size and line height of "Learn More " button text. should be 14px and 20px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/00b00232-09d6-4a96-bfb8-038df4a3d701)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f0b6c4e5-812c-4ffb-b7f2-9a467904bfc5)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
