### ISSUE TITLE
ADHD - Listed In social buttons are not the same as the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#226]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adhd

Description:
 Listed In social buttons are not the same as the design

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d3669e32-38a5-437a-b75c-398a97a638da)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1a7a0c89-a5da-4b6f-b126-97445975fc4f)

**Comment by awais-abbas-com** [comment]
Fixed
