### ISSUE TITLE
Blog Listing - Featured Post Section - All issues generic to ADHD page, section "ADHD information" (Both sections are same)

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#227]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
 Featured Post Section - All issues generic to ADHD page, section "ADHD information" (Both sections are same)

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c60f39b4-1a47-4b83-9b0a-9c9224540884)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/70483e5f-6543-4efd-826d-2dc6f33f6097)

**Comment by awais-abbas-com** [comment]
posts are coming from blog
