### ISSUE TITLE
Page - Team

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#23]
Need to create Team page following Desktop and Mobile Designs.

Follow General guidelines including :
Follow Mobile First and optimized approach for code.
Commented Code
Create Modules with generic options including typography/containers/spaces/background and button panels.
Every text/image should be editable in HubSpot Edit Settings.

Design URLs
Desktop: https://www.dropbox.com/scl/fo/4sypz9vv6wsbdkbv5jcy3/h?rlkey=uqr21opgegjfgjvfmdrpamry6&dl=0
Mobile: https://www.dropbox.com/scl/fo/fudd4a4aa3hkmjf57wubc/h?rlkey=6w689s827bsjem7zhvylahmbq&dl=0

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the Team. Please follow the instructions mentioned above for details.

Page URL's:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/team

**Comment by awais-abbas-com** [comment]
Task has been completed.
