### ISSUE TITLE
Blog Listing - incorrect border radius of the "See More" button. it should be 19 on each side.

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#236]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
incorrect border radius of the "See More" button. it should be 19 on each side.

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/914c2c9e-24ce-4fee-b5f2-80fac165d568)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6e21c992-12f3-40eb-92e8-802d04149332)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
