### ISSUE TITLE
Blog Listing - side paddings are off

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#237]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
side paddings are off

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e916a86d-c77f-4f45-b11a-41b039c6d391)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/679f0f5d-d9a1-4b75-a1c3-986fd70b731c)

**Comment by touqeer-haider-com** [comment]
@mahreen-hashmi-com , Please check on 1920

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
