### ISSUE TITLE
Blog Listing - "All blog post" cards have incorrect width height and radius. it should be W= 1619, H = 375 and border-radius should be 16px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#238]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
"All blog post" cards have incorrect width height and radius. it should be W= 1619, H = 375 and border-radius should be 16px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/8d3c31e8-6339-473d-8a59-d893144b454c)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c15a84ac-9fde-4b13-b7d2-ffe57e5164bb)

**Comment by awais-abbas-com** [comment]
Fixed
