### ISSUE TITLE
Blog Listing - The "Take our assessment" button has incorrect width height, and border radius. It should be W= 290 and H = 54. The border-radius should be 27px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#239]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
The "Take our assessment" button has incorrect width height, and border radius. It should be W= 290 and H = 54. The border-radius should be 27px.

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b6ca2094-fb69-49e0-9b2b-d37bdda96319)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cc23df8f-56b9-4a2d-ba6d-18472dc1ed3b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
