### ISSUE TITLE
Blog Listing - Banner edge yelllow spot position is not fine

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#240]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
Banner edge yelllow spot position is not fine

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/fb111cc6-6838-49b4-8cf1-2deee16c7ec2)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4a804276-32c6-45cf-973f-7b7ce753b22b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
