### ISSUE TITLE
Blog Listing - Mobile - banner text has incorrect size and line height. It should be 17px and 27px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#242]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
the banner text has the incorrect size and line height. It should be 17px and 27px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3d0ab4cc-1b6d-436b-bae6-18a952986cbb)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d20ceb33-6a81-4dbf-899e-f20f5fa37714)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
