### ISSUE TITLE
Blog Listing - Mobile - "Featured Posts" and "All blog posts" headings have incorrect font size and line height. It should be 25px and 28px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#243]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
"Featured Posts" and "All blog posts" headings have incorrect font size and line height. It should be 25px and 28px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/949d7574-3a90-4e55-82f6-94a8c4ecbd57)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/01f144df-ce94-490e-92c1-7293a051467f)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
