### ISSUE TITLE
Blog Listing - Mobile - Featured Post Section - All issues generic to ADHD page, section "ADHD information" (Both sections are same)

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#244]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
Featured Post Section - All issues generic to ADHD page, section "ADHD information" (Both sections are same)
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/1a3f3811-49e0-41e1-ba6e-f251ad5cf63f)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/29a39547-1ee1-4b8c-a788-8ee6cf0c1d06)

**Comment by awais-abbas-com** [comment]
Posts are auto generated
