### ISSUE TITLE
Blog Listing - Mobile - All blog post cards Title, has incorrect font size and line height. It should be 14px and 20px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#245]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
All blog post cards' titles have incorrect font sizes and line heights. It should be 14px and 20px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cf3dda01-df7d-46bd-9cc0-bee9626bf86e)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4cc45dcf-1f33-48b4-afa2-5a3cd0ef7d21)

**Comment by awais-abbas-com** [comment]
Fixed
