### ISSUE TITLE
Blog Listing - Mobile - read more button has incorrect font size and line height. It should be 9px and 12px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#246]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
read more button has incorrect font size and line height. It should be 9px and 12px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4843f007-fff2-4d62-8528-f772d342ccb7)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/38bccffa-8cc6-4664-a526-0d1ab808195f)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
