### ISSUE TITLE
Blog Listing - "Sign up today" copy text, has incorrect font size and line height. it should be 18px and 28px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#248]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
"Sign up today" copy text, has incorrect font size and line height. it should be 18px and 28px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/30419e6b-38aa-4e79-b1d2-518d12c3c86b)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e8626991-1268-4bc7-9ec3-af7b1127bee1)

**Comment by awais-abbas-com** [comment]
Fixed
