### ISSUE TITLE
Blog Listing - "Form fields" placeholders have incorrect font size, and line height. It should be 9px semi bold and 12px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#249]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
"Form fields" placeholders have incorrect font size and line height. It should be 9px, and 12px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/5acd7238-bccf-4c8c-984d-3d7b5f05b428)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c5c1ffb0-b308-42fa-8c83-c4b56dd7cf13)

**Comment by awais-abbas-com** [comment]
Fixed
