### ISSUE TITLE
Blog Listing - Mobile - personalize process heading has incorrect font size and line height. It hsould be 25px and 28px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#250]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
personalize process heading has incorrect font size and line height. It should be 25px and 28px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7d28fe63-9f71-426c-b769-c7b02a489589)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/fed2eeda-9cb4-414f-9abb-565a3d187e43)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
