### ISSUE TITLE
Blog Listing - The "Take our assessment" button has incorrect width height, and border radius. It should be W= 187 and H = 35. The border-radius should be 17p

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#252]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
The "Take our assessment" button has incorrect width height, and border radius. It should be W= 187 and H = 35. The border-radius should be 17px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/232a7051-b151-4939-9207-f7f6db77a7f9)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6fc24d51-1581-47d0-9285-e437f0ccb568)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
