### ISSUE TITLE
Blog Listing - The forn fields, place hoders text are not same to the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#253]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
The form fields, place holders text are not the same to the design

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e82185dd-5fec-439a-9136-41cb4c390877)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/151c511e-bfa8-416f-8617-746789f0a237)

**Comment by awais-abbas-com** [comment]
Fixed
