### ISSUE TITLE
Blog Listing - Mobile - incorrect spacing betweet cards and incorrect size of cards

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#254]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
 incorrect spacing between cards and incorrect size of cards
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f2447d7d-2367-412d-9269-769b044eeabc)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/bb5f79e4-3668-41bc-b662-692110097aa4)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
