### ISSUE TITLE
Blog Listing - no validations are applied on the Form, accepting empty form.

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#255]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
no validations are applied on the Form, accepting empty form.

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/97a271ed-40a3-4907-b055-a19c1c25ad89)

![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/de87d4c3-d763-47d5-aa7c-14bc738c9a12)

**Comment by awais-abbas-com** [comment]
Fixed
