### ISSUE TITLE
Team - banner heading has incorrect line height. it should be 99px as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#256]
URL Tested:
https://www.beyondbooksmart.com/beyond-2024-test-blog

Description:
banner heading has incorrect line height. it should be 99px as per the  design

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/fcdc1058-d071-4d93-be28-63f79c336b99)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/20c0b412-6548-4b04-9071-6411a1c349f6)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
