### ISSUE TITLE
Team - banner copy text has incorrect line height. it should be 33px as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#257]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
banner copy text has incorrect line height. it should be 33px as per design

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/6bac44a8-1922-4236-8c39-4647968b6218)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/7d2347c7-4a19-4a91-a84c-5a89373bfc2a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
