### ISSUE TITLE
Team - Desktop- Mobile - Take our assessment section - Generic issues to other pages 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#259]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
Take our assessment section has generic issues to other pages for desktop and mobile.

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/c633c050-9aed-4943-ae40-f04a4fcae19c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
