### ISSUE TITLE
Team - Mobile - On cards, the designation has incorrect font weight

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#260]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
On cards, the designation has an incorrect font weight
Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/e01ffa41-d6ef-40e3-926f-bb14385a8676)

Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/d20ba324-406b-456d-b44d-661a36e62e3d)

**Comment by awais-abbas-com** [comment]
Fixed
