### ISSUE TITLE
Team - Mobile - Banner, the icon is at the end of the text but currently the text is at the end

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#261]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
on Banner, the icon is at the end of the text but currently the text is at the end
Device: Mobike

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/55fa0efe-a089-4714-b113-e3567a531948)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/0529a966-73c4-48eb-98ad-70a857cd18a6)

**Comment by awais-abbas-com** [comment]
Design bug, we will follow desktop version
