### ISSUE TITLE
Team - Mobile - Meet the leadership heading should be adjusted as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#262]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
Meet the leadership heading should be adjusted as per the design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/d7f5d4e5-4500-4a1b-b2f4-d27ad00bfbc8)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/1b349521-843b-42e7-99dd-38a14de3ff90)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. It is continuous Texts.
