### ISSUE TITLE
Team - images are cutting on responsiveness

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#263]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

Description:
 images are cutting on responsiveness

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/522470be-baa3-47a2-87e2-bb96be1e27f6)

**Comment by awais-abbas-com** [comment]
Fixed
