### ISSUE TITLE
Adults - School -  banner copy text has incorrect line height. It should be 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#264]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
banner copy text has incorrect line height. It should be 47px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/96eceb04-cf84-496d-9159-2813049713c7)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/32ff0d53-8310-4dcc-9d5f-ce33901f1808)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
