### ISSUE TITLE
Adults - School - Introducing Worksmart heading has incorrect line height. It should be 72px as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#265]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
Introducing Worksmart heading has incorrect line height. It should be 72px as per the design

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/684aaf8b-33a9-4535-9670-dab75fe603ab)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/7ae8e7a3-3d65-4c66-943c-98d400666f17)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
