### ISSUE TITLE
Adults - Schools - Meet the worksmart coaching heading has incorrect line height. It should be 72px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#266]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
Meet the work smart coaching heading has incorrect line height. It should be 72px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/9249f05d-747a-4d1c-881a-2c09b99154a0)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/ebd19a4f-af1b-41ae-88bc-4d0a376b49f2)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
