### ISSUE TITLE
Adults - Learn more copy text has incorrect line height. it should be 47

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#267]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
Learn more copy text has incorrect line height. it should be 47

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/c6268f16-1dda-4fad-a969-2c610b64eaff)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/bcddc800-7642-4103-96a8-cf2d1d34fb10)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
