### ISSUE TITLE
Adults - ADHD Support section has incorrect heading and content as per design. it should be Adult ADHD Support instead Student ADHD Support

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#268]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
ADHD Support section has incorrect heading and content as per design. it should be Adult ADHD Support instead Student ADHD Support

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/53c2cf13-444b-4609-8e64-5227a6d8f34f)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/fcb19460-3ee3-4e37-b42f-e4869e365e59)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
