### ISSUE TITLE
Students - Banner --Banner height is incorrect it should be 819 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#269]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Banner height is incorrect it should be 819 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/de7afd20-6e7d-401d-bf63-5757523f660e)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/b643ec9a-cce8-4b36-833d-dacfc8aa5577)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
