### ISSUE TITLE
Students - Banner -- banner paragraph line height is incorrect it should be 47.25 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#270]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
banner paragraph line height is incorrect it should be 47.25 

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/f29a7cdf-6ad3-458a-bfb0-2d051b2cb974)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/3d022470-36a0-4ccc-820c-97b078333d1b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
