### ISSUE TITLE
Adult  - Mobile - Introducing WorkSmart Coaching heading has incorrect font size and line height. it should be 25px and 30px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#274]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
Introducing WorkSmart Coaching heading has incorrect font size and line height. it should be 25px and 30px
 Mobile 

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/72b84c44-de19-4aac-b650-450617547407)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/df3ffec3-3c00-42fe-90d9-4d1f24c6629e)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
