### ISSUE TITLE
Student - Beyond  Academic  Achievement -- H3 Heading line height is incorrect it should be 47.25 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#275]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
H3 Heading line height is incorrect it should be 47.25 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/77e4d689-b1fa-4c25-9aac-9790cc6ef3a7)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/3f4f68f9-4df9-4e38-8a6c-ac055dd6270f)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
