### ISSUE TITLE
Adult  - Mobile - How executive function heading has incorect font size and line height. It should be 25px and 28px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#276]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
How executive function heading has incorrect font size and line height. It should be 25px and 28px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/87c670f6-ba39-4bb3-9f76-ac6536dc1175)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/a14ca291-130c-45c5-92ab-1d2fbe64eb86)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
