### ISSUE TITLE
Students - Our Approach -- Heading line height is incorrect it should be 72 px 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#277]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Heading line height is incorrect it should be 72 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/6b2cf15f-699d-4356-8a28-23cee5bba288)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/feadf10e-b64c-41c1-a138-41886150f22f)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
