### ISSUE TITLE
Adult - Mobile - How executive function heading copy text has incorrect font size and line height. It should be 12px and 20px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#278]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
How executive function heading copy text has incorrect font size and line height. It should be 12px and 20px
Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/012e0e1a-0480-42c9-b5c1-0a9793ad0df9)

Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/d51a2a70-8a84-4cd2-a6e7-7b51166c2ea5)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
