### ISSUE TITLE
Students - Our Approach , Our Parents, Learn More

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#281]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
same as #273 

**Screenshot**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/16156945-6bd6-4e75-8f78-aed68c4cf1e9)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e20de0aa-9315-491a-ae6d-c5b3e6364a0a)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/87382533-c6d4-4c13-891f-8ea9979643b0)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
