### ISSUE TITLE
Adult - Mobile - Adult ADHD support heading has incorrect font size and line height. It should be 25px and 29px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#282]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

Description:
The adult ADHD support heading has incorrect font size and line height. It should be 25px and 29px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/4144d6c2-6c4b-4d93-9791-21c088a26f2d)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/b2a99ed0-2659-4da5-8a17-e17d03c4a835)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
