### ISSUE TITLE
Adult - Schools - Mobile - meet the worksmart heading has incorrect font size and line height. It should be 25px and 30px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#283]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
 meet the worksmart heading has incorrect font size and line height. It should be 25px and 30px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/604c0d43-350f-4914-a3ad-0ecde1806454)

Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/315922bc-4b7e-45ee-886c-53aefc2caed4)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
