### ISSUE TITLE
Students - Learn More --paragraph text line height is incorrect it should be 47.25 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#284]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
paragraph text line height is incorrect it should be 47.25 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/6fc211da-8f2f-4ac3-9df7-5eb2610d74bc)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/0368ad8b-79eb-472c-91d5-d40ee03dc9b2)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
