### ISSUE TITLE
Adult - Schools - Mobile - Learn more heading has incorrect font size and line height. It should be 25px and 44px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#285]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
Learn more heading has incorrect font size and line height. It should be 25px and 44px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/a2a31b19-706e-4cd6-9d0c-c59dc1135ddc)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/66b79f08-0d43-407a-8ecd-0f64bf7764ae)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
