### ISSUE TITLE
Students - Caoching: what to Expect -- Ui shape size is incorrect it should be 312.59 x 169.904 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#286]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Ui shape size is incorrect it should be 312.59 x 169.904 

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e83a9d4c-7f78-4744-b0f1-ab581ba0ed34)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7b6ffa80-2d13-42ef-9efe-c32289610141)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
