### ISSUE TITLE
Students - Caoching: what to Expect -- stroke size is incorrect it should be 21 x 13 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#287]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
 stroke size is incorrect it should be 21 x 13

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/a7aeaa8d-d6bb-44b4-9e02-a7081642dfbd)
**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/8d06ce83-4b99-4823-b5ea-a5696299a9d8)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
