### ISSUE TITLE
Students - Beyond Academic Achievement -- gradient circle needs to be moved a little to the right side 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#290]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
gradient circle needs to be moved a little to the right side 

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/d224d49e-d68c-483f-b054-5dc5cabe659b)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/90469338-6ab5-4706-87d6-da80158b01f1)

**Comment by awais-abbas-com** [comment]
Fixed
