### ISSUE TITLE
Student - Meet the BBS team -- image size is incorrect it should be 786 x 737

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#292]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
image size is incorrect it should be 786 x 737

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/338a2fb5-ecfd-42ee-a202-12289b504bf5)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/9edc5b8c-632a-4140-a023-e600bbf78988)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. Images are adjusted within width.
