### ISSUE TITLE
Student - For Parents -- image size is incorrect it should be 132 x 174

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#293]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
image size is incorrect it should be 132 x 174

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/9ea2d9b2-0aea-4f30-b9bc-a36be454748c)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/9fe7edd9-14e8-48cf-8eab-0a39700898ff)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
