### ISSUE TITLE
Student - Banner --top and bottom padding of section is incorrect it should be 135 on top and 118 on bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#296]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding of section is incorrect it should be 135 on top and 118 on bottom

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e9f847ee-6479-4241-8a4c-7276e35d8c5f)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/9285b8a1-8559-4747-b5ed-c45e18a2877f)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/2d690d58-dc64-4de2-9974-e6b5d22bf4ad)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
