### ISSUE TITLE
Student - Banner -- padding between the heading and paragraph is incorrect it should be 18 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#297]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between the heading and paragraph is incorrect it should be 18 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7b43a04a-d3a7-4844-80cb-ff76ef47cfeb)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/8acd000a-5469-4350-aa2a-bffd454db045)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
