### ISSUE TITLE
Students - Caoching: what to Expect --section top padding and bottom padding is incorrect it should be 109 from top and 129 from bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#299]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
section top padding and bottom padding are incorrect it should be 109 from the top and 129 from the bottom

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/8848101f-fc9a-458c-bf22-81b3f8cc4afd)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/3ed5571c-3fd0-4550-a84f-8f968a24c73d)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/f20505f1-abe1-4f2a-811a-a04c6bdf195b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. There is line-height factor as well, spaces need to managed with that in Development.
