### ISSUE TITLE
Students - Caoching: what to Expect -- top padding of bullet points is incorrect it should be 61 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#301]
**URL**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top padding of bullet points is incorrect it should be 61 px

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/ea885025-247b-4146-9e84-772aefa1fc8e)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/70374d8a-5ef2-451a-8727-e80d3807893c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
