### ISSUE TITLE
Student - Student ADHD Support -- padding between paragraph and button is incorrect it should be 82 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#304]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between paragraph and button is incorrect it should be 82 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/5fd28928-bc0e-43aa-9c4a-64ae4eb92264)
**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/33ff2978-267f-4c2c-a784-72cf81f156d7)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
