### ISSUE TITLE
Student - Student ADHD Support -- Heading width is incorrect it should be 585 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#305]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Heading width is incorrect it should be 585 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/8834bb42-34db-43cc-9299-e5398dca7c0a)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/0d08286a-e649-4fb9-aafc-b93fe60753b4)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
