### ISSUE TITLE
Student - Student ADHD Support -- padding between heading and paragraph is incorrect it should be 262 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#306]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between the heading and paragraph is incorrect it should be 262 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e4dc87b0-d6eb-4b17-9f35-803e112f4366)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/5dfe4f35-bbe4-450a-af0b-3560e538d9f7)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
