### ISSUE TITLE
Student - Student ADHD Support -- Top and bottom padding is incorrect it should be 144 on top and 197 on bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#307]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Top and bottom padding is incorrect it should be 144 on top and 197 on bottom

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e9217bb8-c758-4677-9bca-23141b1cbd10)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/9f5223cb-61d1-47db-ac2e-c2cf9b8c1a11)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/0edb96ea-dc06-4847-b12e-0a9e7ea2cf56)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
