### ISSUE TITLE
Student - Beyond Academic Achievement -- padding between the two side content is incorrect it should be 100 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#309]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between the two side content is incorrect it should be 100 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/759534eb-e815-4c7d-b1d8-4de0c52c6e1f)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e043b439-f2fd-41b7-8c37-a56df84c35ba)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
