### ISSUE TITLE
Student - Beyond Academic Achievement -- row gap is incorrect it should be 100 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#310]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
row gap is incorrect it should be 100 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/a541ce26-9736-4e9b-b1eb-41868ad1f44b)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/d308ff2e-1eed-4fc1-afbc-07647a3996aa)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
