### ISSUE TITLE
Student - Beyond Academic Achievement --heading has incorrect bottom padding it should be 55 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#312]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
heading has incorrect bottom padding it should be 55 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/13603396-4c2a-44a0-8b52-162fb3a8eba2)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/29444381-500d-44a4-8a77-7d7c04032a56)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
