### ISSUE TITLE
Student - Our Approach -- h3 heading has incorrect top & bottom padding it should be 51 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#313]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
h3 heading has incorrect top & bottom padding it should be 51 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/77abf75b-87e5-43dd-a607-73bf96abc020)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/bc6cd270-bd34-4d46-a12b-788a729f55a3)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/63e9d8c3-5b47-4022-807e-febbe40f4504)

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/976beeff-e589-4e46-872e-0da70d41dcdc)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
