### ISSUE TITLE
Student - Meet the BBS team -- top and bottom padding is incorrect it should be 120 from top and 130 from bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#314]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding is incorrect it should be 120 from the top and 130 from the bottom

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/61ae75b5-1949-4c92-ba51-79dc5f9aad22)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/1a2adb51-d751-4a6b-934e-2df8749810b0)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/b2766b69-0732-46fa-8871-5d5616acc516)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
