### ISSUE TITLE
Student - Meet the BBS team -- padding between paragraph and button is incorrect it should be 80 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#315]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between paragraph and button is incorrect it should be 80 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/34fcec94-2f7d-4305-9997-05cb5dea2510)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/4c425ea6-2379-43e9-a631-d17be9313770)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
