### ISSUE TITLE
Student - For Parents -- top and bottom padding is incorrect it should be 95 for the top and 87 for the bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#316]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding is incorrect it should be 95 for the top and 87 for the bottom

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/1760a1f9-288c-499b-a53f-2358890d04fe)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/08f5eb84-6a02-405b-a6ca-7f02527ea2f9)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/0d2a0b62-38dd-4cdd-8651-e7c603c24ecd)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
