### ISSUE TITLE
Student - For Parents -- top padding of button is incorrect it should be 50 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#317]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top padding of button is incorrect it should be 50 px

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/1d4e2cbe-76c6-429c-9955-13e561f7e442)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/6ab3b86a-602a-4523-9076-3758fd25b028)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
