### ISSUE TITLE
Student - Learn more -- top and bottom padding is incorrect it should be 87 from the top and 52 from the bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#318]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding is incorrect it should be 87 from the top and 52 from the bottom

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7104ad95-c3a5-44ed-bc7e-35e99f4efd80)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e5a5e3d4-61ca-4cce-aaaf-d414faaa2cec)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/ee7f1ac3-f3ca-4641-90fd-9934cace2d25)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
