### ISSUE TITLE
Student -  Banner -- image size is incorrect it should be 275 x 215 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#321]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
image size is incorrect it should be 275 x 215 

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/4282a7c7-304e-4374-8ed9-d4084a0d8a0a)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e055417a-c549-4113-ba00-4c8dbaf3acf7)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. Image adjusted with in container
