### ISSUE TITLE
Student - Banner -- padding between image and paragraph is incorrect it should be 40 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#322]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
padding between image and paragraph is incorrect it should be 40 px

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/33306d4b-9ea4-4081-84b5-8099be958bf1)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/55caceb4-584f-4568-ac5c-e2603d7d5c3a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
