### ISSUE TITLE
Student - Coaching: what to expect -- font size and line height is incorrect it should be 25 px and 30 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#324]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
font size and line height is incorrect it should be 25 px and 30 px

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7a1076ad-2afd-4bc3-b93a-d840d7170163)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/f5bc4846-5bc1-4be5-954b-cfe92be0469c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
