### ISSUE TITLE
Student - Coaching: what to expect -- font size and line height is incorrect it should be 12 px and 17 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#325]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
font size and line height is incorrect it should be 12 px and 17 px

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/5b371e86-af64-4c3d-abb9-51142d7cce62)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/ec61aa6c-8e37-4dae-a22b-cbf267cb8558)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
