### ISSUE TITLE
Student - Student ADHD Support -- top padding of button is incorrect it should be 35 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#327]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
The top padding of a button is incorrect it should be 35 px

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/01caad2b-6bb9-4f09-b8c6-f5d0d49dbe71)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7e2a84fb-0a43-4684-baa7-b7ec41c0a94c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
