### ISSUE TITLE
Student - Beyond Academic  Achievement -- top and bottom padding is incorrect it should be 35 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#328]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding is incorrect it should be 35 px

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/821242d3-d5fb-4e99-b29c-6f1ccf937c6e)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/b1f5c37f-542a-4efa-9bf9-7d87a77f3f05)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/fbac84e3-33c1-4626-aba4-571baa4ca5f4)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
