### ISSUE TITLE
Student - Beyond Academic Achievement -- font size and line height are incorrect it should be 25 and 28 px respectively

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#329]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
font size and line height are incorrect it should be 25 and 28 px respectively

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e5ee0d67-61ea-44e4-8a0a-3ddb41f6340a)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/72e68352-11d9-4bd5-8d10-c5c66b221138)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
