### ISSUE TITLE
Student - Beyond Academic Achievement -- icon size is incorrect it should be 309 x 760

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#330]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
icon size is incorrect it should be 309 x 760

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e1c9a320-016f-4e02-b15f-173b11f4e75c)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/26ad73ee-b881-4d18-93cc-b0c84f8e501b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
