### ISSUE TITLE
Student - Beyond Academic Achievement --  h3 heading bottom padding is incorrect it should be 20 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#331]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
h3 heading bottom padding is incorrect it should be 20 px

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/1d9cbac0-d6ef-41d9-acba-e5323cfdbe9b)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/3a049ba4-0d67-497b-8606-279670685e08)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
