### ISSUE TITLE
Student - Our Approach -- top and bottom padding is incorrect it should be 30 px for top and 45 for bottom padidng

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#333]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
top and bottom padding is incorrect it should be 30 px for top and 45 for bottom padidng

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/b4c201aa-f304-4294-8150-b1c6f66455af)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/1c6aac81-110d-4b24-92ed-8ba33ab68d91)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/00ba9082-c373-4ac2-89c6-c34b4e6ca02b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
