### ISSUE TITLE
Student - Our Approach -- Heading font size and line height are incorrect it should be 25 and 31 px respectively

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#334]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
 Heading font size and line height are incorrect it should be 25 and 31 px respectively

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/cc7b979b-951d-4efb-acf1-74ff31e0d996)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/fcba4ee1-f838-4dc5-81c2-84b961116f66)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
