### ISSUE TITLE
Student - Our Approach -- Heading font size and line height are incorrect it should be 14 and 14 px respectively

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#335]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Bug**
Heading font size and line height are incorrect it should be 14 and 14 px respectively

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e29ecd6b-0d4c-4e0e-9f21-72a0a3a78987)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/43015de7-9153-428f-ab32-09de3a527179)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
