### ISSUE TITLE
Student - Our Approach --  the space between paragraph and H3 heading is incorrect it should be 71 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#336]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students#

**Bug**
the space between paragraph and H3 heading is incorrect it should be 71 px

**Devices**
Mobile

**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/2b249328-5c00-46ee-87fb-79928bc4671c)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/f882aaf8-8cc0-44b4-adfc-c980f1a2ae65)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
