### ISSUE TITLE
Student - Meet the BBS team -- top and bottom padding are incorrect it should be 50 px on top and 35 on bottom

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#337]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students#

**Bug**
top and bottom padding are incorrect it should be 50 px on top and 35 on bottom

**Devices**
Mobile

**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/e05961b7-8e7c-4b33-a7c9-f5dee2a0787a)

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/7e5a4941-45cb-4c9d-a270-72e24242f6b9)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/5c173008-c223-42db-b671-ea7a5cf42315)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
