### ISSUE TITLE
Student - Meet the BBS team , The Parents, 

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#339]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students#

**Bug**
same as https://github.com/ComputanTeam/enticedge-beyondbooksmart/issues/324

**Screenshot**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/39403a08-b80a-4bf6-b233-1e12de31ccc5)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
