### ISSUE TITLE
 Student - The parents -- padding between paragraph and button should be 30 px

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#340]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students#

**Bug**
padding between paragraph and button should be 30 px

**Device**
Mobile

**Screenshot**
**Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/55c7fa0c-9fdd-4fb0-b5e6-444385300067)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/14760c5f-4359-42ee-b038-4dc693d3bd38)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
