### ISSUE TITLE
Student - The parents -- image size is incorrect it should be 297 x 288

### ISSUE THREAD

**Issue by maria-farooq-com** [ComputanTeam/enticedge-beyondbooksmart#341]
**Url**
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students#

**Bug**
image size is incorrect it should be 297 x 288

**Device**
Mobile

**Screenshot
Expected**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/2cab09c0-5163-4f22-a093-50374ac94621)

**Actual**
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/129780439/17157162-60c9-4c0e-bd3b-54a6bcda0cb1)

**Comment by awais-abbas-com** [comment]
Images are following from desktop
