### ISSUE TITLE
School - Mobile - how executive heading has incorrect font size and line height. it should be 23px and 27px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#344]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
how executive heading has incorrect font size and line height. it should be 23px and 27px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/e33e1f89-a767-4346-9791-f910f41e6a5f)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/2e4d3971-bcc1-4df8-84b9-68e9e4fe179d)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
