### ISSUE TITLE
School - Mobile - how executive cards heading has incorrect font size and line height. it should be 15px and 25px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#345]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
how executive cards heading has incorrect font size and line height. it should be 15px and 25px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/94e1eff6-8191-4036-b82f-7087af0a2c54)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/cc89378a-c511-4b4e-a77a-a9c2c92e02c7)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
