### ISSUE TITLE
Schools - Mobile - "braintracks helped" heading has incorrect line height. It should be 21px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#346]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
"braintracks helped" heading has incorrect line height. It should be 21px
Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/fa3825f9-5e4a-4b60-acd4-04b2e99adb34)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/ccc9f629-3d44-431d-b136-66266f6d86e5)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
