### ISSUE TITLE
Schools - Mobile - "School Counselor, Green Woods Charter School, Philadelphia, PA" has incorrect font size and line height. It should be 13px and 18px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#347]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
"School Counselor, Green Woods Charter School, Philadelphia, PA" has incorrect font size and line height. It should be 13px and 18px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/b1c8a887-697d-4dc4-a389-e1709ecb2612)

Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/7cfd24cf-c561-4be3-8307-8611d24d5ac3)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
