### ISSUE TITLE
Schools - The learn more button is missing from below the How executive cards

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#348]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
The learn more button is missing from below the How executive cards

Actual Result: Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/cebcd8ae-fc58-46c4-9a1f-461bd359bbe2)

**Comment by awais-abbas-com** [comment]
Following Desktop content
