### ISSUE TITLE
QC - Adults

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#35]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/6
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the Adults stage page. Please follow the instructions mentioned above for details.

Page URL:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/adults

**Comment by awais-abbas-com** [comment]
Task has been completed.
