### ISSUE TITLE
Schools - Mobile -  Meet the brainTracks Team -image and text placement issue, there should be an image, and then below the image, there should be text as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#350]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
 Meet the brainTracks Team -image and text placement issue, there should be an image, and then below the image, there should be text as per design

Actual Result: Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/5f9a6563-f769-4998-9fca-ffab5b67812b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
