### ISSUE TITLE
Adults - Schools - ADHD Information section - Learn More section - Lets get started section - BBS review section - Listed In Read on section has generic issues to other pages

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#351]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/schools

Description:
ADHD Information section 
- Learn More section 
- Let's Get Started section 
- BBS review section 
- Listed In Read on section has generic issues to other pages

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
