### ISSUE TITLE
Privacy Policy - banner heading is incorrect as per the design it should be "Privacy Notice"

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#352]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/privacy-policy

Description:
banner heading is incorrect as per the design it should be "Privacy Notice"

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/97146d87-4e71-49b5-9633-3506bd8ceddb)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/e4ccca84-370f-45ca-9138-ff2644b52d1f)

**Comment by awais-abbas-com** [comment]
Fixed
