### ISSUE TITLE
Privacy Policy - baaner copy text has incorrect line height. it should be 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#353]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/privacy-policy

Description:
baaner copy text has incorrect line height. it should be 47px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/683d95b8-d176-423f-9b1a-4efdfbbe8077)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/31c64d7c-c5a0-445c-9834-fe9ac8aa8aa2)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. Updates done from client as well.
