### ISSUE TITLE
Privacy Policy - last updated heading has incorrect font size, weight and line height. it should be 14px Bold and 31px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#354]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/privacy-policy

Description:
The last updated heading has incorrect font size, weight, and line height. it should be 14px Bold and 31px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/f1267e28-4269-4a48-9bfe-aea6badb61a2)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/854776a4-c2f7-4a34-b568-335cae7c8496)

**Comment by awais-abbas-com** [comment]
Fixed
