### ISSUE TITLE
Privacy Policy - responsiveness issue

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#356]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/privacy-policy

Description:
responsiveness issue on resizing.
device: 1023

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/749b2dca-707d-46e0-92f3-ce4b4e8afee0)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
