### ISSUE TITLE
How it Works - "Why Beyond BookSmart for coaching?" has incorrect text, font size and line height. It should be "Why BBS coaching?" and 72px and 107px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#357]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
"Why Beyond BookSmart for coaching?" has incorrect text, font size, and line height. It should be "Why BBS coaching?" and 72px and 107px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/83373f6b-16c2-4f7a-a020-908deac2055b)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/58722307-bfa0-40ff-8861-6be9de46706a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
