### ISSUE TITLE
How it Works - An inside look at a BBS Coaching Session headings copy text has incorrect font size and line height. it should be 24px and 43px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#358]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
An inside look at a BBS Coaching Session headings copy text has incorrect font size and line height. it should be 24px and 43px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/173aa458-e6b2-44e4-b2e0-ae9712ad305f)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/f59d43bb-7beb-4039-abdd-12d13fb6d3ae)

**Comment by awais-abbas-com** [comment]
Fixed
