### ISSUE TITLE
How it Works -  "An inside look at a BBS Coaching Session" has incorrect font size and line height. It should be 72px and 88px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#359]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
"An inside look at a BBS Coaching Session" has incorrect font size and line height. It should be 72px and 88px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/3de3fe37-1469-440a-8b74-16a80d098622)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/8303e8ab-a6a9-447d-bb3f-7d30f20dd7a4)

**Comment by awais-abbas-com** [comment]
H2 is mostly used in in such kind of sections so we kept it as H2
