### ISSUE TITLE
How it Works -  Expand bar copy text has incorrect line height. It should be 33px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#361]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
Expand bar copy text has incorrect line height. It should be 33px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/feb89c9e-1e21-4975-bfe9-d8bd4f57c02c)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/727dfcc3-14c0-411f-b6b8-38db21418bf6)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
