### ISSUE TITLE
How it Works - CTA title for sceduling has incorrect font size and line height. it should be 48px and 55px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#364]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
The CTA title for scheduling has incorrect font size and line height. it should be 48px and 55px

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/4121256d-93e2-4b23-81d7-ea2829d2ce41)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/a551171c-2982-4f71-9b24-470269107bba)

**Comment by awais-abbas-com** [comment]
Fixed
