### ISSUE TITLE
How it Works - Mobile - Coaching: what to expect, checkpoints has incorrect font size and line height. it should be 12px and 17px 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#366]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
Coaching: what to expect, checkpoints have incorrect font size and line height. it should be 12px and 17px 
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/df1cd137-3c5f-4fc4-809a-57dd757fa31f)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/43bf0051-bdad-4771-878b-5330939b76e6)

**Comment by awais-abbas-com** [comment]
Fixed
