### ISSUE TITLE
How it Works - Mobile - Why BBS coaching? has incorrect font size and line height. it should be 25px and 30px 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#367]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
Why BBS coaching? has incorrect font size and line height. it should be 25px and 30px 
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/ce0bc5a6-74cf-4b30-a8d9-9bc7d53ce6fa)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/844d8077-57b0-404d-945a-93efdf202ac0)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
