### ISSUE TITLE
How it Works - Mobile - An inside look at a BBS Coaching Session copy text has incorrect font size and line height. it should be 15px and 27px 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#368]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
An inside look at a BBS Coaching Session copy text has incorrect font size and line height. it should be 15px and 27px 
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/a0df0907-6b89-4bff-a1ab-0e3e11f839cc)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/04ea6220-3a61-4815-8d8d-a6e3f9ed3b62)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
