### ISSUE TITLE
How it Works - Mobile - Learn More should be in the center as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#372]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
 Learn More should be in the center as per the design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/2c0cfeea-cca5-4225-9165-b7b560f46b9c)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/b5fc5f32-2dfa-4439-b45e-3616046bec8b)

**Comment by awais-abbas-com** [comment]
Fixed
