### ISSUE TITLE
How it Works - Mobile - the "CTA title for scheduling a call goes here" heading has incorrect font size and line height. it should be 25px and 30px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#374]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
 The "CTA title for scheduling a call goes here" heading has incorrect font size and line height. it should be 25px and 30px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/d70472b1-b5f9-4c9d-b310-18c3f5c5ab84)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/64427fc6-4836-4a0b-8829-91fa37bc38d9)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
