### ISSUE TITLE
How it Works - Mobile - The "Schedule a call" button has the incorrect size and border-radius. it should be width 150px and height 35px. border-radius should be 17px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#375]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
The "Schedule a call" button has the incorrect size and border-radius. it should be width 150px and height 35px. border-radius should be 17px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/752d0bf2-0775-48db-96e6-d0385202c5dc)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/ac36fdbd-7e95-433c-a219-a8f311fe37d4)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. Buttons going generic.
