### ISSUE TITLE
How it Works - Mobile - incorrect size of images as per design and images should be in the center

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#376]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
incorrect size of images as per design and images should be in the center
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/7064d6cb-c203-44cc-b8be-32886b7b82a5)
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/5650641d-b211-4f8c-94b0-a9bb7dcb70cd)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
