### ISSUE TITLE
How it Works - Mobile - incorrect size of "Coaching: what to expect" cards. it should be 282px and 459px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#377]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
incorrect size of "Coaching: what to expect" cards. it should be 282px and 459px
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/8acd6add-9a47-4819-8af2-73cebc29f41b)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/118c1dcf-9b70-434c-b4f2-b5666c6f874b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
We need to take care about shadow and also taking care on smaller screens as well to show the next item properly.
