### ISSUE TITLE
How it Works - Mobile - incorrect Tom-Bottom spacings of  "Coaching: what to expect" cards. it should be same per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#378]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
incorrect Tom-Bottom spacings of  "Coaching: what to expect" cards. it should be the same per design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/c7d20567-0bc9-4206-98a1-753356745d97)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/d279f561-c2a7-4780-b471-5b4c392ff377)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
