### ISSUE TITLE
How it Works - Mobile - An inside look heading has incorrect background color. it should be as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#379]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
An inside looking heading has an incorrect background color. it should be as per the design
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/9d4a0c1a-5337-49b0-ac9e-ae9b517301ae)

Expected Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/25234662-9b68-4056-b53d-e4b46168c444)

**Comment by awais-abbas-com** [comment]
Fixed
