### ISSUE TITLE
How it Works - "An inside look" heading copy text, needs to adjust the text properly. Currently, it's not aligned

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#380]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
"An inside look" heading copy text, needs to adjust the text properly. Currently, it's not aligned
Device: Mobile

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/57261e21-eb8a-487c-9621-7875794bc428)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/0bc5c120-a2b8-4e6d-81be-cb8559707841)

**Comment by awais-abbas-com** [comment]
fixed
