### ISSUE TITLE
How it Works - Need to adjust top bottom paddings of thje section as per the design and left-right padding should stay consistent on resizing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#381]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
We need to adjust the top-bottom paddings of the section as per the design and left-right padding should stay consistent on resizing
Device: any

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/fdd88ae9-584b-4c88-aed1-556ed4e254cc)

Expected Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/e5620620-b133-4ab1-974b-f78399856104)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
