### ISSUE TITLE
How it Works - Learn More video is not smooth on full screen or turning off fullscreen

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#382]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

Description:
Learn More video is not smooth on full screen or turning off fullscreen

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/64068748-581f-479b-9f45-d589333d3d54)

**Comment by awais-abbas-com** [comment]
It is with plugin and working fine
