### ISSUE TITLE
Footer - Need to apply hover and phone number should be intel tag

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#384]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Need to apply hover and phone number should be intel tag

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/624787a9-68fd-470c-ad76-8d34b165a222)

**Comment by awais-abbas-com** [comment]
Fixed
