### ISSUE TITLE
Footer - Wrong size of log

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#386]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong size of log

Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/c5edfd0b-1d6d-40a1-aedd-69c424536072)

**Comment by awais-abbas-com** [comment]
Fixed
