### ISSUE TITLE
Footer - Wrong font size

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#387]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong font size

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/e7d62f6c-6663-4600-8c4a-f101c625aa18)

**Comment by awais-abbas-com** [comment]
Fixed
