### ISSUE TITLE
Footer - Wrong size of circle should be 30px or 32px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#388]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong size of circle should be 30px or 32px
Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/86a64001-904a-4274-a098-c66d63e55b59)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
