### ISSUE TITLE
Footer - Arrow missing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#390]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Arrow missing
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/686d8df2-6a31-4250-a39f-d3cdeb47a5c1)

**Comment by awais-abbas-com** [comment]
Fixed
