### ISSUE TITLE
Footer - Year should be 2024 it should be handled with function

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#393]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Year should be 2024 it should be handled with function
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/1aa0458c-5989-4507-8bfc-b09e59917b23)

**Comment by awais-abbas-com** [comment]
Fixed
