### ISSUE TITLE
Home - Wrong circle border color or border missing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#398]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong circle border color or border missing
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/95d975c3-fc95-401d-ae88-e6d12ba5e992)

**Comment by awais-abbas-com** [comment]
It is simple image takken from design.
