### ISSUE TITLE
QC - Contact Us

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#40]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/11
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the ADHD stage page. Please follow the instructions mentioned above for details.

Page URL:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/contact-us

**Comment by awais-abbas-com** [comment]
Task has been completed.
