### ISSUE TITLE
Home -  Wrong space

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#400]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong space

Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/8ea6a762-5a80-47f7-b1aa-2c51969dbad3)

**Comment by awais-abbas-com** [comment]
Fixed
