### ISSUE TITLE
Home -  Need to apply hover

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#405]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Need to apply hover
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/434de4d3-4d2b-4116-9f9c-eba4a9477f04)

**Comment by awais-abbas-com** [comment]
Fixed
