### ISSUE TITLE
Home -  Box shadow should be editable

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#406]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Box shadow should be editable

Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/a279ea58-10e7-4376-b84e-bbf817edda13)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, circle shadows, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We don't have separate images from shadows and other shapes.
