### ISSUE TITLE
Home -  Text should be in 2 column

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#415]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Text should be in 2 column

Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/3c3a86b7-8fe9-48a2-8fad-066f4549c08d)

**Comment by awais-abbas-com** [comment]
fixed
