### ISSUE TITLE
Home -  Wrong styling of this section and slider missing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#416]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong styling of this section and slider missing
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/14832cd4-0168-4705-a276-6f7894f306c2)

**Comment by awais-abbas-com** [comment]
This is Trustpilot plugin
