### ISSUE TITLE
Contact Us - Border radius missing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#417]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Border radius missing
Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/2b50c304-4a28-4b0c-81c4-6e063c12056a)

**Comment by awais-abbas-com** [comment]
This is widget auto generated from Hubspot
