### ISSUE TITLE
Contact Us - Wrong alignment of tick sign and text

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#420]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong alignment of tick sign and text
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/4e1c404c-f560-40f4-a17a-627aef5fa161)

**Comment by awais-abbas-com** [comment]
Fixed
