### ISSUE TITLE
Contact Us - Need to remove horizontal scroll

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#423]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Need to remove horizontal scroll
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/67896ea3-375b-419f-b5ea-ca5f85f6016c)

**Comment by awais-abbas-com** [comment]
This is in widget actually.
