### ISSUE TITLE
Contact Us - Border styling missing

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#424]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Border styling missing

Actual Result:
![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/5942b73e-6cdd-4502-ac0c-6a593313bae6)

**Comment by awais-abbas-com** [comment]
We dont have design for this widget.
