### ISSUE TITLE
Contact Us - Wrong alignment

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#426]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Wrong alignment
Actual Result:

![image](https://github.com/ComputanTeam/enticedge-beyondbooksmart/assets/132403977/aa1b7df4-7fc3-4aa3-9bdc-fcfa8430052b)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks.
