### ISSUE TITLE
QC - How It Works

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#44]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/15
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the stage page on the How It Works. Please follow the instructions mentioned above for details.

Page URL's:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/how-it-works

**Comment by awais-abbas-com** [comment]
Task has been completed.
