### ISSUE TITLE
QC - Students

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#51]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/22
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the Students stage page. Please follow the instructions mentioned above for details.

Page URL:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/students

**Comment by awais-abbas-com** [comment]
Task has been completed.
