### ISSUE TITLE
QC - Team

### ISSUE THREAD

**Issue by muhammad-suleman-com** [ComputanTeam/enticedge-beyondbooksmart#52]
```[tasklist]
### Tasks
- [ ] https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/issues/23
```

**Comment by muhammad-suleman-com** [comment]
Kindly review the URL to the Team stage page. Please follow the instructions mentioned above for details.

Page URL:-
https://www-beyondbooksmart-com.sandbox.hs-sites.com/teams

**Comment by awais-abbas-com** [comment]
Task has been completed.
