### ISSUE TITLE
Home - Section Get Unfrustrated - the incorrect line height of the banner's copy text. it should be 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#53]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
the incorrect line height of the banner's copy text. it should be 47px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/4dd424fd-71be-43a6-81db-50e6c8bb347e)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f5afde5e-5bd1-4b7e-b28b-ea757f9e6e1c)

**Comment by muhammad-suleman-com** [comment]
We create our design files using Illustrator. We have verified the spacing and alignment using fonts and AI, ensuring a close match. The typography, spacing, and alignment are standardized for a consistent user experience.
