### ISSUE TITLE
Home - Section Get Unfrustrated - The banner checklist has incorrect line height. It should be 51px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#55]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The banner checklist has incorrect line height. It should be 51px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/bced2341-49f8-433d-9cbc-41c7c5638766)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/32567985-d07e-4b5a-b931-0358422d335f)

**Comment by muhammad-suleman-com** [comment]
We create our design files using Illustrator. We have verified the spacing and alignment using fonts and AI, ensuring a close match. The typography, spacing, and alignment are standardized for a consistent user experience.
