### ISSUE TITLE
Home - Section Get Unfrustrated - Incorrect size of banners checklist icon. it should be width 21px height 13px  (size 2.5px) 

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#58]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Incorrect size of banners checklist icon. it should be width 21px height 13px  (size 2.5px) .

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e9799df5-c094-4fde-a326-2cd9df9b0b17)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/513f2ea5-0f3f-47d7-9424-ef6beaae970f)

**Comment by muhammad-suleman-com** [comment]
We have conducted a thorough check of the spacing and alignment using fonts and AI, achieving a close match. The typography, spacing, and alignment are kept generic to maintain a consistent user experience.
