### ISSUE TITLE
Home - Section Get Unfrustrated - banner checklist icon has an incorrect color. it should be #1F9CC0 but it is #009ec4

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#59]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The banner checklist icon has an incorrect color. it should be #1F9CC0 but it is #009ec4

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/825ec24c-c693-49fe-98af-00635aec43ef)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/8c7caa53-f1ab-4427-bbde-27ef4a1e136b)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d3fcb8a1-634c-44a8-9ee9-f78a0afe4d60)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
