### ISSUE TITLE
Home - Section Get Unfrustrated - Incorrect top-bottom padding of the banner. it should be 138px on top and 121px on the bottom

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#60]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Incorrect top-bottom padding of the banner. it should be 138px on top and 121px on the bottom

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/84c82f0b-3f71-4a32-a388-3783e904fd47)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/8f22ef0a-a17f-41a2-ae5f-d486d5efe23e)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/497dfdff-cdab-4592-84a7-f9d91d6b36db)

**Comment by muhammad-suleman-com** [comment]
Our design files are created using Illustrator. We have carefully examined the spacing and alignment using fonts and AI, aiming for a close match. The typography, spacing, and alignment are kept consistent to provide a uniform user experience.
