### ISSUE TITLE
Home - Section We Can Help - incorrect line height of icons headings copy text. it should be 33px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#62]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect line height of icon headings copy text. it should be 33px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/46d0fb57-68d9-4896-885e-25a21d669ae5)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/2eb53d39-220e-48e4-902e-884b06e71bf4)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We have conducted a thorough check of the spacing and alignment using fonts and AI, achieving a close match. The typography, spacing, and alignment are kept generic to maintain a consistent user experience.
