### ISSUE TITLE
Home - Section We Can Help - Incorrect line height of Learn More button. it should be 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#63]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Incorrect line height of Learn More button. it should be 47px

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/861c5589-5b07-4b74-a2c9-cda46b115e3a)

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/368f4ebf-becf-42ae-887e-a9f9b539128a)

**Comment by muhammad-suleman-com** [comment]
Our design files are created using Illustrator. We have carefully examined the spacing and alignment using fonts and AI, aiming for a close match. The typography, spacing, and alignment are kept consistent to provide a uniform user experience
