### ISSUE TITLE
Home - Section We Can Help - the position of the underline below the Main heading is not per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#64]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
the position of the underline below the Main heading is not per the design
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/5ee4b962-8884-4f5c-b3ce-6926ae0054f6)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/80e08693-7305-4e36-90bb-c936265a6394)

**Comment by awais-abbas-com** [comment]
Fixed
