### ISSUE TITLE
Home - Section We Can Help - incorrect left-right paddings . it should be 196px as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#65]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 incorrect left-right paddings. it should be 196px as per the design

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/f64a70c0-42d2-42bc-bad7-e101be2de8e6)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/ce4dc946-f958-4089-87b7-d28ceb4754dd)

**Comment by muhammad-suleman-com** [comment]
We have examined the spacing and alignment using fonts and AI, making sure they closely match. The typography, spacing, and alignment are standardized to provide a consistent user experience.
