### ISSUE TITLE
Home - Section We Can Help - incorrect line width as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#66]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect line width as per the design
Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/46bebdd5-d596-4533-9688-b841d0d88b28)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e797d134-952e-4776-9ba7-7fc2bee4b664)

**Comment by muhammad-suleman-com** [comment]
We have examined the spacing and alignment using fonts and AI, making sure they closely match. The typography, spacing, and alignment are standardized to provide a consistent user experience.
