### ISSUE TITLE
Home - Section How It Works - cards headings has incorrect line height. it should be 47px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#68]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards headings has incorrect line height. it should be 47px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7c4f4d93-b4f8-486d-a9cf-1b172e0800f4)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b5df0b9e-ada3-447f-bd22-186832327544)

**Comment by muhammad-suleman-com** [comment]
We have conducted a thorough check of the spacing and alignment using fonts and AI, achieving a close match. The typography, spacing, and alignment are kept generic to maintain a consistent user experience.
