### ISSUE TITLE
Home - Section How It Works - cards count icons have incorrect width * height .and color . It should be 68 * 68 and #1F9CC0

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#71]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
cards count icons have incorrect width * height and color. It should be 68 * 68 and #1F9CC0

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b84ba32a-1af3-4767-a8a2-f6cf8a67ab5a)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/984f655a-dcde-408c-ba9e-e7ad5ee7728a)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
