### ISSUE TITLE
Home - Section How It Works - the slider arrows have incorrect height and width, and color. it should be the width = 11px and height 23px, and color should be #1F9CC0

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#73]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
the slider arrows have incorrect height and width, and color. it should be the width = 11px and height 23px, and color should be #1F9CC0

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/be44854a-4963-46a1-abb8-f5d2d52d9523)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/da1f6285-2526-4c04-810b-f4d63e69f547)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/dc75b306-4416-42c0-82f2-e939d2dbc1d1)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
