### ISSUE TITLE
Home - Section How It Works - incorrect left-right paddings . it should be 149px as per design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#74]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 incorrect left-right paddings. it should be 149px as per design

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cb0b4de2-70a7-4368-8b09-851584c40598)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/cb0b4de2-70a7-4368-8b09-851584c40598)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
