### ISSUE TITLE
Home - Meet The Coaches - Incorrect line height of "Learn More" button text . it should be 25px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#81]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
Incorrect line height of "Learn More" button text . it should be 25px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/e30e4299-7fea-408f-9623-01b8f2bab731)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/882ef49b-0e8a-4b12-9a3b-d33fe3157790)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
