### ISSUE TITLE
Home - Section Meet The Coaches -  "Learn More" button has incorrect size. It should be width 198px and height 57px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#82]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 The "Learn More" button has an incorrect size. It should have a width 198px and a height 57px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d0b5ccd7-6b20-4dc7-805f-b42f60d45ef0)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3e75eda4-1325-42af-bb50-c622a70e4923)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
