### ISSUE TITLE
Home - Section Meet The Coaches - the incorrect bottom padding of the section - it should be 103px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#83]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 the incorrect bottom padding of the section - it should be 103px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/530b0f29-50a4-445e-b5c8-0eb8705c3875)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/21147f1b-6daa-4308-b5b4-ed7149b2e16f)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
