### ISSUE TITLE
Home - Section Meet The Coaches - no blue design in the photos as per the design

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#85]
URL Tested:
https://dvk.developmentpreviews.com/

Description:
no blue design in the photos as per the design

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/619d1cd0-b5b5-47aa-a214-08dc8dbb1427)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/3c36a23d-65dc-4b70-9166-ac8089f00f31)

**Comment by awais-abbas-com** [comment]
Images are sliced from AI, shadows different in XD also we need to keep it inside the container. Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
