### ISSUE TITLE
Home - Sections What Are Those - checklist text has incorrect line height and color - it should be 51px and #000000

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#88]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
checklist text has incorrect line height and color - it should be 51px and #000000

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/86210397-5d6a-4ca1-8368-66570673e917)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/666e7ad6-70e7-4c3f-93f9-eb8e8b7f1fce)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
