### ISSUE TITLE
Home - Sections What Are Those - Incorrect placement (design) of the image

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#91]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
 Incorrect placement (design) of the image

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/bdf7d6cb-a613-4a07-b3bf-9d2c359a4f9a)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/7e050a44-264e-456a-b9a9-bb80da89077b)

**Comment by awais-abbas-com** [comment]
Fixed
