### ISSUE TITLE
Home - Section Serve Our Client's - The heading has incorrect line height and color. it should be 65px and #1E1E30

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#92]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The heading has incorrect line height and color. it should be 65px and #1E1E30

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/9b5e1cc4-5250-4aa3-9d65-d7d2fa901d5f)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/d34d2f29-2f56-4dbc-a668-948ecc0db97c)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
