### ISSUE TITLE
Home - Section Serve Our Client's - "Learn More " button has the incorrect size and color. it should be width 188px and height 54px and color should be #FFD100 (generic color issue for all buttons)

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#95]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
"Learn More " button has the incorrect size and color. it should be width 188px and height 54px and color should be #FFD100 (generic color issue for all buttons)

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/c9be8d9b-0841-41fa-a61a-4775d2b78924)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/daa4ec02-b351-40d8-b8de-e8650bafa390)

**Comment by awais-abbas-com** [comment]
Actual design files are in Illustrator, We have checked spaces with installed fonts and via AI file. Alignment and spaces maximum matched with original design files in AI. Also We kept the typography, spaces and alignment generic and equalized to maintain user experience better for same kind of blocks. We have discuss with the client and following general and one color scheme for better User Experience. https://i.imgur.com/erunEjx.png
