### ISSUE TITLE
Home - Section Serve Our Client's - incorrect top-bottom and left-right padding of the section. It should be top-bottom 116px/129px and sides should be 343px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#97]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
incorrect top-bottom and left-right padding of the section. It should be top-bottom 116px/129px and sides should be 343px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b3362ee5-ce65-4c93-a97f-fd46d7673a22)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b601b7f7-2851-4db7-b986-ddd018d2d2da)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/07825461-a88e-4f96-929a-255f55f2781c)
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/5ef789b4-ea0e-4e13-ab19-022989ecd5fa)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
