### ISSUE TITLE
Home - Section Let's Get Started - "Learn more" button text have incorrect size and line height. It should be 28px and 30px

### ISSUE THREAD

**Issue by mahreen-hashmi-com** [ComputanTeam/enticedge-beyondbooksmart#98]
URL Tested:
https://www-beyondbooksmart-com.sandbox.hs-sites.com/home-new-theme

Description:
The "Learn more" button text has incorrect size and line height. It should be 28px and 30px

Actual Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/b687e536-f582-4cbb-8485-ea473cf8ee7e)

Expected Result:
![image](https://github.com/ComputanTeam/EnticEdge-Beyondbooksmart/assets/132403977/6ee083ea-d620-4b5d-9316-e2d966a9c327)

**Comment by muhammad-suleman-com** [comment]
Our design files are made with Illustrator. We've checked the spacing using fonts and AI and matched alignment as closely as possible. Typography, spacing, and alignment are generic for a consistent user experience.
